version: '3.8'

services:
  postgres:
    container_name: nest_vue_db
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}"
      
  app:
    container_name: nest_vue
    build:
      context: ./
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "${API_LOCAL_PORT}:${API_PORT}"
    environment:
      API_PORT: ${API_PORT}
      API_LOCAL_PORT: ${API_LOCAL_PORT}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_LOCAL_PORT: ${POSTGRES_LOCAL_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      ACCESS_TOKEN_TIME: ${ACCESS_TOKEN_TIME}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      REFRESH_TOKEN_TIME: ${REFRESH_TOKEN_TIME}